dist: trusty
language: cpp
compiler: clang
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-6.0
      - ubuntu-toolchain-r-test
    packages:
      # LLVM
      - llvm-6.0-dev
      # Tcl
      - tcl8.6-dev
      # For testing
      - tcl8.6
install:
  - ./configure CC=$CXX --with-llvm-config=llvm-config-6.0
script:
  - make
  - make test
