dist: trusty
language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
      - ubuntu-toolchain-r-test
    packages:
      - llvm-4.0
      - llvm-4.0-dev
      - libstdc++-6-dev
      - libc++
install:
  - ./configure
script:
  - make
  - make test
