dist: trusty
language: cpp
compiler: clang
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
      - ubuntu-toolchain-r-test
    packages:
      - clang-4.0
      - llvm-4.0
      - llvm-4.0-dev
install:
  - ./configure --with-llvm-config=llvm-config-4.0
script:
  - make
  - make test
